import type { VehicleCategory } from '@/types/vehicle'
import { Vehicle } from '@/types/vehicle'

export const WHATSAPP_NUMBER = '5511999999999'

export const vehicles: Vehicle[] = [
  {
    id: '1',
    slug: 'mercedes-benz-a35-amg',
    brand: 'Mercedes-Benz',
    model: 'A35 AMG',
    year: 2020,
    price: 320000,
    mileage: 25000,
    category: 'carro',
    status: 'disponivel',
    description: 'Hot hatch esportivo premium com tração integral 4MATIC e motor turbo de 306cv.',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80',
    features: ['4MATIC', 'Teto Solar', 'MBUX', 'Câmera de Ré', 'Rodas AMG 19"'],
    highlighted: true,
    color: 'Prata',
    fuel: 'Gasolina',
  },
  {
    id: '2',
    slug: 'honda-africa-twin-2023',
    brand: 'Honda',
    model: 'Africa Twin CRF1100L',
    year: 2023,
    price: 79900,
    mileage: 8000,
    category: 'moto',
    status: 'disponivel',
    description: 'A lendária Africa Twin em excelente estado, com todas as revisões em dia.',
    image: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3c87?w=800&q=80',
    features: ['DCT', 'Controle de Tração', 'ABS', 'Modos de Condução', 'GPS Integrado'],
    highlighted: true,
    color: 'Tricolor',
    fuel: 'Gasolina',
  },
  {
    id: '3',
    slug: 'ktm-rc-390',
    brand: 'KTM',
    model: 'RC 390',
    year: 2022,
    price: 35000,
    mileage: 12000,
    category: 'moto',
    status: 'disponivel',
    description: 'Esportiva leve e ágil, perfeita para track days e curvas no fim de semana.',
    image: 'https://images.unsplash.com/photo-1449426468159-d96dbf08f19f?w=800&q=80',
    features: ['ABS Cornering', 'Embreagem Deslizante', 'Quickshifter', 'Painel TFT'],
    highlighted: true,
    color: 'Laranja/Branco',
    fuel: 'Gasolina',
  },
  {
    id: '4',
    slug: 'ferrari-laferrari',
    brand: 'Ferrari',
    model: 'LaFerrari',
    year: 2015,
    price: 25000000,
    mileage: 2000,
    category: 'carro',
    status: 'disponivel',
    description: 'O hipercarro híbrido definitivo. V12 aspirado de 800cv mais motor elétrico, totalizando 963cv.',
    image: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&q=80',
    features: ['Motor V12 Híbrido', 'Fibra de Carbono', 'Freios de Cerâmica', 'Aerodinâmica Ativa'],
    color: 'Rosso Corsa',
    fuel: 'Híbrido',
  },
  {
    id: '5',
    slug: 'vw-golf-gti-stage1',
    brand: 'Volkswagen',
    model: 'Golf GTI Mk7 Stage 1',
    year: 2017,
    price: 98000,
    mileage: 72000,
    category: 'tuning',
    stage: 'Stage 1',
    status: 'disponivel',
    description: 'Golf GTI com reprogramação de fábrica Stage 1, extraindo mais 50cv do motor 2.0 TSI.',
    image: 'https://images.unsplash.com/photo-1541443131876-44b03de101c5?w=800&q=80',
    features: ['Remap Stage 1', 'Escapamento Sport', 'Suspensão Ajustada', 'LSD', 'Rodas 19"'],
    color: 'Branco Puro',
    fuel: 'Gasolina',
  },
  {
    id: '6',
    slug: 'toyota-hilux-2021',
    brand: 'Toyota',
    model: 'Hilux SRX 2.8 TDI 4x4',
    year: 2021,
    price: 189900,
    mileage: 38000,
    category: 'carro',
    status: 'disponivel',
    description: 'A lenda da robustez. Hilux SRX completa, automática, 4x4. Perfeita para trabalho e aventura.',
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80',
    features: ['4x4 Automático', 'Teto Solar', 'Couro', 'Multimídia 8"'],
    highlighted: false,
    color: 'Branco Pérola',
    fuel: 'Diesel',
  },
  {
    id: '7',
    slug: 'yamaha-r6',
    brand: 'Yamaha',
    model: 'YZF-R6',
    year: 2020,
    price: 75000,
    mileage: 15000,
    category: 'moto',
    status: 'disponivel',
    description: 'Uma lenda nas pistas. A superesportiva média mais cobiçada, com motor girador e ciclística afiada.',
    image: 'https://images.unsplash.com/photo-1609630875171-b1321377ee65?w=800&q=80',
    features: ['Controle de Tração', 'QuickShifter', 'Modos de Pilotagem', 'ABS'],
    color: 'Amarelo/Preto',
    fuel: 'Gasolina',
  },
  {
    id: '8',
    slug: 'fiat-500',
    brand: 'Fiat',
    model: '500',
    year: 2014,
    price: 45000,
    mileage: 60000,
    category: 'carro',
    status: 'reservado',
    description: 'O clássico italiano com design atemporal. Ágil para a cidade, econômico e estiloso.',
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80',
    features: ['Teto Panorâmico', 'Direção Elétrica', 'Modo City', 'Rodas de Liga Leve'],
    color: 'Azul Claro',
    fuel: 'Gasolina',
  },
  {
    id: '9',
    slug: 'ford-ranger-raptor-stage3',
    brand: 'Ford',
    model: 'Ranger Raptor Stage 3',
    year: 2019,
    price: 210000,
    mileage: 55000,
    category: 'tuning',
    stage: 'Stage 3',
    status: 'disponivel',
    description: 'Ranger Raptor com preparação Stage 3 completa. Motor 2.0 Biturbo remapeado, suspensão long travel.',
    image: 'https://images.unsplash.com/photo-1559416523-140ddc3d238c?w=800&q=80',
    features: ['Remap Stage 3', 'Suspensão Long Travel', 'Snorkel', 'Pneus BFGoodrich'],
    color: 'Laranja',
    fuel: 'Diesel',
  },
]

export const getVehiclesByCategory = (category: VehicleCategory | 'todos') => {
  if (category === 'todos') return vehicles
  return vehicles.filter(v => v.category === category)
}

export const getVehicleBySlug = (slug: string) => {
  return vehicles.find(v => v.slug === slug)
}

export const formatPrice = (price: number): string => {
  return new Intl.NumberFormat('pt-BR', {
    style: 'currency',
    currency: 'BRL',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price)
}

export const formatMileage = (km: number): string => {
  return new Intl.NumberFormat('pt-BR').format(km) + ' km'
}
