import type { VehicleCategory } from '@/types/vehicle'
import { Vehicle } from '@/types/vehicle'

export const WHATSAPP_NUMBER = '5522999822842'

export const vehicles: Vehicle[] = [
  {
    id: '1',
    slug: 'mercedes-benz-a35-amg',
    brand: 'Mercedes-Benz',
    model: 'A35 AMG',
    year: 2020,
    price: 320000,
    mileage: 25000,
    category: 'hatch',
    status: 'disponivel',
    description: 'Hot hatch esportivo premium com tração integral 4MATIC e motor turbo de 306cv.',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80',
    features: ['4MATIC', 'Teto Solar', 'MBUX', 'Câmera de Ré', 'Rodas AMG 19"'],
    highlighted: true,
    color: 'Prata',
    fuel: 'Gasolina',
  },
  {
    id: '2',
    slug: 'honda-africa-twin-2023',
    brand: 'Honda',
    model: 'Africa Twin CRF1100L',
    year: 2023,
    price: 79900,
    mileage: 8000,
    category: 'moto',
    status: 'disponivel',
    description: 'A lendária Africa Twin em excelente estado, com todas as revisões em dia.',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    features: ['DCT', 'Controle de Tração', 'ABS', 'Modos de Condução', 'GPS Integrado'],
    highlighted: true,
    color: 'Tricolor',
    fuel: 'Gasolina',
  },
  {
    id: '3',
    slug: 'ktm-rc-390',
    brand: 'KTM',
    model: 'RC 390',
    year: 2022,
    price: 35000,
    mileage: 12000,
    category: 'moto',
    status: 'disponivel',
    description: 'Esportiva leve e ágil, perfeita para track days e curvas no fim de semana.',
    image: 'https://images.unsplash.com/photo-1449426468159-d96dbf08f19f?w=800&q=80',
    features: ['ABS Cornering', 'Embreagem Deslizante', 'Quickshifter', 'Painel TFT'],
    highlighted: true,
    color: 'Laranja/Branco',
    fuel: 'Gasolina',
  },
  {
    id: '4',
    slug: 'toyota-corolla-2022',
    brand: 'Toyota',
    model: 'Corolla Altis Hybrid',
    year: 2022,
    price: 165000,
    mileage: 22000,
    category: 'sedan',
    status: 'disponivel',
    description: 'Sedan híbrido premium com acabamento impecável, eficiência superior e máximo conforto.',
    image: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80',
    features: ['Motor Híbrido', 'Couro Bege', 'Head-Up Display', 'Toyota Safety Sense', 'Teto Solar'],
    highlighted: true,
    color: 'Branco Pérola',
    fuel: 'Híbrido',
  },
  {
    id: '5',
    slug: 'vw-golf-gti-stage1',
    brand: 'Volkswagen',
    model: 'Golf GTI Mk7 Stage 1',
    year: 2017,
    price: 98000,
    mileage: 72000,
    category: 'tuning',
    stage: 'Stage 1',
    status: 'disponivel',
    description: 'Golf GTI com reprogramação de fábrica Stage 1, extraindo mais 50cv do motor 2.0 TSI.',
    image: 'https://images.unsplash.com/photo-1541443131876-44b03de101c5?w=800&q=80',
    features: ['Remap Stage 1', 'Escapamento Sport', 'Suspensão Ajustada', 'LSD', 'Rodas 19"'],
    color: 'Branco Puro',
    fuel: 'Gasolina',
  },
  {
    id: '6',
    slug: 'toyota-hilux-2021',
    brand: 'Toyota',
    model: 'Hilux SRX 2.8 TDI 4x4',
    year: 2021,
    price: 189900,
    mileage: 38000,
    category: 'picape',
    status: 'disponivel',
    description: 'A lenda da robustez. Hilux SRX completa, automática, 4x4. Perfeita para trabalho e aventura.',
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80',
    features: ['4x4 Automático', 'Teto Solar', 'Couro', 'Multimídia 8"'],
    highlighted: false,
    color: 'Branco Pérola',
    fuel: 'Diesel',
  },
  {
    id: '7',
    slug: 'yamaha-r6',
    brand: 'Yamaha',
    model: 'YZF-R6',
    year: 2020,
    price: 75000,
    mileage: 15000,
    category: 'moto',
    status: 'disponivel',
    description: 'Uma lenda nas pistas. A superesportiva média mais cobiçada, com motor girador e ciclística afiada.',
    image: 'https://images.unsplash.com/photo-1609630875171-b1321377ee65?w=800&q=80',
    features: ['Controle de Tração', 'QuickShifter', 'Modos de Pilotagem', 'ABS'],
    color: 'Amarelo/Preto',
    fuel: 'Gasolina',
  },
  {
    id: '8',
    slug: 'jeep-compass-2023',
    brand: 'Jeep',
    model: 'Compass Limited 4x4',
    year: 2023,
    price: 198000,
    mileage: 18000,
    category: 'suv',
    status: 'disponivel',
    description: 'SUV premium com motor 1.3 turbo flex, tração 4x4 e pacote de segurança completo.',
    image: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80',
    features: ['4x4 On-Demand', 'Uconnect 10"', 'Couro', 'Keyless', 'Câmera 360°'],
    highlighted: true,
    color: 'Cinza Granite',
    fuel: 'Flex',
  },
  {
    id: '9',
    slug: 'ford-ranger-raptor-stage3',
    brand: 'Ford',
    model: 'Ranger Raptor Stage 3',
    year: 2019,
    price: 210000,
    mileage: 55000,
    category: 'tuning',
    stage: 'Stage 3',
    status: 'disponivel',
    description: 'Ranger Raptor com preparação Stage 3 completa. Motor 2.0 Biturbo remapeado, suspensão long travel.',
    image: 'https://images.unsplash.com/photo-1559416523-140ddc3d238c?w=800&q=80',
    features: ['Remap Stage 3', 'Suspensão Long Travel', 'Snorkel', 'Pneus BFGoodrich'],
    color: 'Laranja',
    fuel: 'Diesel',
  },
  {
    id: '10',
    slug: 'fiat-uno-2019',
    brand: 'Fiat',
    model: 'Uno Drive 1.0',
    year: 2019,
    price: 42000,
    mileage: 55000,
    category: 'hatch',
    status: 'disponivel',
    description: 'Hatch econômico, ágil e perfeito para o dia a dia na cidade. Manutenção em dia.',
    image: 'https://images.unsplash.com/photo-1541038970432-8d2e29bdd7ea?w=800&q=80',
    features: ['Direção Elétrica', 'Vidros Elétricos', 'Travas Elétricas', 'Ar-Condicionado'],
    color: 'Vermelho',
    fuel: 'Flex',
  },
  {
    id: '11',
    slug: 'vw-amarok-2022',
    brand: 'Volkswagen',
    model: 'Amarok V6 Highline',
    year: 2022,
    price: 310000,
    mileage: 28000,
    category: 'picape',
    status: 'disponivel',
    description: 'A rainha das picapes premium. Motor V6 Bi-TDI com 258cv, a mais potente do segmento.',
    image: 'https://images.unsplash.com/photo-1558618047-f54b2e4f8082?w=800&q=80',
    features: ['Motor V6 258cv', '4Motion Permanente', 'Teto Solar', 'Couro Beige', 'Passo Longo'],
    highlighted: true,
    color: 'Prata Reflex',
    fuel: 'Diesel',
  },
  {
    id: '12',
    slug: 'hyundai-creta-2023',
    brand: 'Hyundai',
    model: 'Creta Platinum 1.0 Turbo',
    year: 2023,
    price: 142000,
    mileage: 12000,
    category: 'suv',
    status: 'reservado',
    description: 'SUV compacto líder de vendas. Motor turbo flex com excelente torque e tecnologia de ponta.',
    image: 'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=800&q=80',
    features: ['Teto Solar', 'SmartSense', 'Cockpit Digital', 'Wireless Charging', 'BOSE Sound'],
    color: 'Azul Abyss',
    fuel: 'Flex',
  },
  {
    id: '13',
    slug: 'honda-civic-2022',
    brand: 'Honda',
    model: 'Civic Touring 1.5 Turbo',
    year: 2022,
    price: 168000,
    mileage: 19000,
    category: 'sedan',
    status: 'disponivel',
    description: 'Sedan esportivo com motor 1.5 turbo de 174cv, o mais refinado da categoria.',
    image: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&q=80',
    features: ['Honda Sensing', 'Teto Solar', 'Couro Preto', 'Painel Digital', 'CarPlay/Android Auto'],
    highlighted: false,
    color: 'Azul Obsidiana',
    fuel: 'Gasolina',
  },
  {
    id: '14',
    slug: 'fiat-toro-2022',
    brand: 'Fiat',
    model: 'Toro Ranch 2.0 Diesel',
    year: 2022,
    price: 178000,
    mileage: 32000,
    category: 'picape',
    status: 'disponivel',
    description: 'Picape média com o motor diesel mais forte do segmento, 4x4 e acabamento Ranch exclusivo.',
    image: 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&q=80',
    features: ['Motor 2.0 Diesel 170cv', '4x4', 'Couro Marrom', 'Uconnect 8.4"', 'Freio Trailer'],
    color: 'Marrom Savana',
    fuel: 'Diesel',
  },
  {
    id: '15',
    slug: 'mercedes-sprinter-2021',
    brand: 'Mercedes-Benz',
    model: 'Sprinter 415 CDI Executivo',
    year: 2021,
    price: 290000,
    mileage: 45000,
    category: 'utilitario',
    status: 'disponivel',
    description: 'Van executiva com configuração de luxo para transporte corporativo. Excelente estado.',
    image: 'https://images.unsplash.com/photo-1566473965997-3de9c817e938?w=800&q=80',
    features: ['Poltronas Executivas', 'Ar-Cond. Traseiro', 'Geladeira', 'TV', 'Cortinas'],
    color: 'Branco',
    fuel: 'Diesel',
  },
  {
    id: '16',
    slug: 'vw-delivery-2020',
    brand: 'Volkswagen',
    model: 'Delivery 9.170 DRC',
    year: 2020,
    price: 185000,
    mileage: 88000,
    category: 'utilitario',
    status: 'disponivel',
    description: 'Caminhão de entrega em ótimo estado, com baú refrigerado. Ideal para logística urbana.',
    image: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800&q=80',
    features: ['Baú Refrigerado', 'Câmera de Ré', 'Rastreador', 'Direção Hidráulica'],
    color: 'Branco',
    fuel: 'Diesel',
  },
]

export const getVehiclesByCategory = (category: VehicleCategory | 'todos') => {
  if (category === 'todos') return vehicles
  return vehicles.filter(v => v.category === category)
}

export const getVehicleBySlug = (slug: string) => {
  return vehicles.find(v => v.slug === slug)
}

export const formatPrice = (price: number): string => {
  return new Intl.NumberFormat('pt-BR', {
    style: 'currency',
    currency: 'BRL',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price)
}

export const formatMileage = (km: number): string => {
  return new Intl.NumberFormat('pt-BR').format(km) + ' km'
}
